### ISSUE TITLE
I can't run the test.py

### ISSUE THREAD

**Issue by qiji77** [mrakotosaon/intrinsic_interpolations#3]
when I try to run the test.py I got the error as follow:
retrained_DFAUST: Failed precondition: /home/djq19/workfiles/intrinsic_interpolations/intrinsic_interpolation_pretrained_DFAUST; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "test.py", line 294, in <module>
    eval_reconstruction()
  File "test.py", line 239, in eval_reconstruction
    sess, ops = get_model(batch_size=1, num_point=NUM_POINT)
  File "test.py", line 119, in get_model
    saver_pretrain.restore(sess, MODEL_PATH)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1286, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: 2 root error(s) found.
  (0) Data loss: Unable to open table file /home/djq19/workfiles/intrinsic_interpolations/intrinsic_interpolation_pretrained_DFAUST: Failed precondition: /home/djq19/workfiles/intrinsic_interpolations/intrinsic_interpolation_pretrained_DFAUST; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at test.py:116) ]]
  (1) Data loss: Unable to open table file /home/djq19/workfiles/intrinsic_interpolations/intrinsic_interpolation_pretrained_DFAUST: Failed precondition: /home/djq19/workfiles/intrinsic_interpolations/intrinsic_interpolation_pretrained_DFAUST; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?
         [[node save/RestoreV2 (defined at test.py:116) ]]
         [[save/RestoreV2/_53]]
0 successful operations.
0 derived errors ignored.

Original stack trace for u'save/RestoreV2':
  File "test.py", line 294, in <module>
    eval_reconstruction()
  File "test.py", line 239, in eval_reconstruction
    sess, ops = get_model(batch_size=1, num_point=NUM_POINT)
  File "test.py", line 116, in get_model
    saver_pretrain = tf.train.Saver(tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES))
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 825, in __init__
    self.build()
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 837, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 875, in _build
    build_restore=build_restore)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/home/djq19/anaconda3/envs/ii/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by mrakotosaon** [comment]
Hi @qiji77 
I cannot tell for sure from the error, your trained model (MODEL_PATH) should be in the format: path_to_your_model/name_of_you_model.ckpt Is this your case?

**Comment by qiji77** [comment]
well,I can run test.py now
Thank you very much for your reply
best
